server:
  port: 18091
  shutdown: graceful

spring:
  application:
    name: project
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: PROJECT2
    password: PROJECT2PASSWORD

  liquibase:
    enabled: false
    contexts: project2  # 특정 컨텍스트 지정 가능
    database-change-log-table: false
    database-change-log-lock-table: false
  jpa:
#    database-platform: org.hibernate.dialect.OracleDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG