-- liquibase formatted sql


-- changeset project:1738745134901-1
CREATE TABLE TB_CM_BAT_OPTS (BAT_ID VARCHAR2(64 BYTE) NOT NULL, OPT_SEQ NUMBER NOT NULL, OPT_NM VARCHAR2(256 BYTE), OPT_DESC VARCHAR2(256 BYTE), OPT_DATA VARCHAR2(64 BYTE), RG_DTM date NOT NULL, RGMN VARCHAR2(20 BYTE), CHG_DTM date NOT NULL, CHGNM VARCHAR2(20 BYTE), CONSTRAINT PK_CM_BAT_OPTS PRIMARY KEY (BAT_ID, OPT_SEQ)) ;
COMMENT ON TABLE TB_CM_BAT_OPTS IS '웹 배치 프로그램 옵션 정보';
COMMENT ON COLUMN TB_CM_BAT_OPTS.BAT_ID IS '배치프로그램ID';
COMMENT ON COLUMN TB_CM_BAT_OPTS.OPT_SEQ IS '옵션순서';
COMMENT ON COLUMN TB_CM_BAT_OPTS.OPT_NM IS '옵션명';
COMMENT ON COLUMN TB_CM_BAT_OPTS.OPT_DESC IS '옵션 설명';
COMMENT ON COLUMN TB_CM_BAT_OPTS.OPT_DATA IS '옵션 값';
COMMENT ON COLUMN TB_CM_BAT_OPTS.RG_DTM IS '등록일시';
COMMENT ON COLUMN TB_CM_BAT_OPTS.RGMN IS '등록자';
COMMENT ON COLUMN TB_CM_BAT_OPTS.CHG_DTM IS '수정일시';
COMMENT ON COLUMN TB_CM_BAT_OPTS.CHGNM IS '수정자';
